//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayseriEnt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class cbo_Gorev
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public cbo_Gorev()
        {
            this.Sicil = new HashSet<Sicil>();
        }
    
        public int ID { get; set; }
        public string Ad { get; set; }
        public Nullable<System.DateTime> baslangic { get; set; }
        public Nullable<System.DateTime> bitis { get; set; }
        public Nullable<int> sabah { get; set; }
        public Nullable<int> oglen { get; set; }
        public Nullable<int> aksam { get; set; }
        public Nullable<int> gece { get; set; }
        public Nullable<int> toplam { get; set; }
        public Nullable<int> toplu_alim { get; set; }
        public Nullable<int> ziyaretci { get; set; }
    
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Sicil> Sicil { get; set; }
    }
}
