//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayseriEnt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Duty
    {
        public int Id { get; set; }
        public string TargetDevice { get; set; }
        public string Process { get; set; }
        public string userID { get; set; }
        public string Owner { get; set; }
        public Nullable<System.DateTime> RecordDate { get; set; }
        public Nullable<System.DateTime> ProcessDate { get; set; }
        public string TimeZoneID { get; set; }
        public string DeviceMessage { get; set; }
    }
}
