//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayseriEnt.Model
{
    using System;
    using System.Data.Entity;
    using System.Data.Entity.Infrastructure;
    using System.Data.Entity.Core.Objects;
    using System.Linq;
    
    public partial class KAYSERIData : DbContext
    {
        public KAYSERIData()
            : base("name=KAYSERIData")
        {
        }
    
        protected override void OnModelCreating(DbModelBuilder modelBuilder)
        {
            throw new UnintentionalCodeFirstException();
        }
    
        public virtual DbSet<cbo_Bolum> cbo_Bolum { get; set; }
        public virtual DbSet<cbo_Firma> cbo_Firma { get; set; }
        public virtual DbSet<cbo_Gorev> cbo_Gorev { get; set; }
        public virtual DbSet<cbo_Pozisyon> cbo_Pozisyon { get; set; }
        public virtual DbSet<Duty> Duty { get; set; }
        public virtual DbSet<Tasnifleme> Tasnifleme { get; set; }
        public virtual DbSet<Tbl_Birimler> Tbl_Birimler { get; set; }
        public virtual DbSet<UserList> UserList { get; set; }
        public virtual DbSet<Tbl_SicilArac> Tbl_SicilArac { get; set; }
        public virtual DbSet<Sicil> Sicil { get; set; }
    
        public virtual int TumTerminallereYetkiVer(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TumTerminallereYetkiVer", userIDParameter);
        }
    
        public virtual int TumPersonelTerminallereYetkiVer(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TumPersonelTerminallereYetkiVer", userIDParameter);
        }
    
        public virtual int TumRFIDTerminallereYetkiVer(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TumRFIDTerminallereYetkiVer", userIDParameter);
        }
    
        public virtual int TumPersonelTerminallereYasakVer(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TumPersonelTerminallereYasakVer", userIDParameter);
        }
    
        public virtual int TumRFIDTerminallereYasakVer(string userID)
        {
            var userIDParameter = userID != null ?
                new ObjectParameter("UserID", userID) :
                new ObjectParameter("UserID", typeof(string));
    
            return ((IObjectContextAdapter)this).ObjectContext.ExecuteFunction("TumRFIDTerminallereYasakVer", userIDParameter);
        }
    }
}
