//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayseriEnt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tasnifleme
    {
        public int ID { get; set; }
        public int SicilID { get; set; }
        public System.DateTime Giris { get; set; }
        public int GirisID { get; set; }
        public int GirisKayitTipi { get; set; }
        public Nullable<System.DateTime> Cikis { get; set; }
        public int CikisID { get; set; }
        public int CikisKayitTipi { get; set; }
        public int MesaiSuresi { get; set; }
        public int HamFazlaMesai { get; set; }
        public int NormalMesai { get; set; }
        public int OnaylananFazlaMesai { get; set; }
        public int FazlaMesai { get; set; }
        public int ErkenMesai { get; set; }
        public int FazlamesaiOran { get; set; }
        public int EksikmesaiOran { get; set; }
        public int ResmiTatil { get; set; }
        public string MesaiAciklama { get; set; }
        public int IzinTip { get; set; }
        public int IzinSaat { get; set; }
        public Nullable<int> MesaiPeriyodu { get; set; }
        public int Mesaigrubu { get; set; }
        public int Mesaibirimi { get; set; }
        public bool Ayrinti { get; set; }
        public int Tatil { get; set; }
        public bool C24pass { get; set; }
        public bool Kilit { get; set; }
        public bool Ucretli { get; set; }
        public int ResmiTatilMesai { get; set; }
        public int GeceVardiya { get; set; }
        public int Hakedis { get; set; }
        public bool UpdateLock { get; set; }
        public Nullable<System.DateTime> MesaiTarih { get; set; }
        public int Izinsaat2 { get; set; }
        public Nullable<System.DateTime> ggiris { get; set; }
        public Nullable<System.DateTime> Index { get; set; }
        public Nullable<System.DateTime> gcikis { get; set; }
        public Nullable<int> xfm1 { get; set; }
        public Nullable<int> xfm1Oran { get; set; }
        public Nullable<int> fmneden { get; set; }
        public Nullable<int> xfm2 { get; set; }
        public Nullable<int> xfm2Oran { get; set; }
        public Nullable<int> AraSure { get; set; }
        public Nullable<int> IzinID { get; set; }
        public string MesaiOzetAciklama { get; set; }
        public string ITFAciklama { get; set; }
        public string SGFAciklama { get; set; }
        public Nullable<int> ToplamIzinSuresi { get; set; }
        public Nullable<int> UcretliIzinSure { get; set; }
        public Nullable<int> UcretsizIzinSure { get; set; }
        public string IzinIdList { get; set; }
    
        public virtual Sicil Sicil { get; set; }
    }
}
