//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace KayseriEnt.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class Tbl_SicilArac
    {
        public int Id { get; set; }
        public int SicilId { get; set; }
        public int AracSicilId { get; set; }
        public string AracPlaka { get; set; }
        public string RuhsatNo { get; set; }
        public string Aciklama { get; set; }
        public string CepTelefonu { get; set; }
        public bool Deleted { get; set; }
        public Nullable<System.DateTime> DateCreated { get; set; }
        public string Marka { get; set; }
        public string Model { get; set; }
    }
}
